server:
  port: 8200

spring:
  application:
    name: domysuma-website-api
  main:
    allow-bean-definition-overriding: true

  datasource:
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/domysuma2?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Africa/Nairobi
    hikari:
      max-lifetime: 300000

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  jackson:
    parser:
      allow-unquoted-control-chars: true
    property-naming-strategy: SNAKE_CASE
    serialization:
      fail-on-empty-beans: false
      write-dates-as-timestamps: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: thesmitter1@gmail.com
    password: qhtcvcnavegwkxnd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            required: true
            enable: true

  security:
    user:
      name: domysuma-api
      password: domysuma-api

    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: "http://localhost:8200/login/oauth2/code/google"
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            client-name: Google

        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
            user-name-attribute: sub

      resourceserver:
        jwt:
          public-key-location: classpath:rsa.public.key

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha

jwt:
  key:
    private: classpath:rsa.private.key
    public: classpath:rsa.public.key
  expiration-in-hours:
    access: 8760
    refresh: 8760

app:
  frontend:
    url: http://localhost:4200   # Angular dev environment URL

s3:
 accessKey: ${AWS_ACCESS_KEY}
 secretKey: ${AWS_SECRET_KEY}
 endpoint: s3.eu-central-1.amazonaws.com
 region: eu-central-1
 bucket: domysumake
